services:
  application:
    build: .
    restart: always
    ports:
      - 8050:5000
    depends_on:
      - redis
      - database
      - celery-worker
    env_file:
      - env.docker

  database:
    image: postgres
    hostname: database
    volumes:
      - database:/var/lib/postgresql
    ports:
      - "5432:5432"
    env_file:
      - env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: "celery --app app worker --loglevel=info"
    restart: always
    env_file:
      - env.docker
    depends_on:
      - redis
      - database

  mock-file-server:
    hostname: mock-file-server
    image: httpd:alpine
    volumes:
      - ./tests/data:/usr/local/apache2/htdocs/
    ports:
      - "80:80"

  database-migrate:
    build: .
    command:  flask db upgrade
    env_file:
      - env.docker
    depends_on:
      database:
        condition: service_healthy

volumes:
  database:
