services:

  importer-app:
    build: .
    restart: always
    ports:
      - 8050:5000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  importer-db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql
    ports:
      - "5435:5432"
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: "celery --app make_celery worker --loglevel=info"
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  database:
