"""first migration

Revision ID: b63b963c41d7
Revises: 
Create Date: 2024-11-21 06:17:57.815849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63b963c41d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hvfhs_license_num', sa.String(), nullable=True),
    sa.Column('dispatching_base_num', sa.String(), nullable=True),
    sa.Column('originating_base_num', sa.String(), nullable=True),
    sa.Column('request_datetime', sa.DateTime(), nullable=True),
    sa.Column('on_scene_datetime', sa.DateTime(), nullable=True),
    sa.Column('pickup_datetime', sa.DateTime(), nullable=True),
    sa.Column('dropoff_datetime', sa.DateTime(), nullable=True),
    sa.Column('PULocationID', sa.Integer(), nullable=True),
    sa.Column('DOLocationID', sa.Integer(), nullable=True),
    sa.Column('trip_miles', sa.Float(), nullable=True),
    sa.Column('trip_time', sa.Integer(), nullable=True),
    sa.Column('base_passenger_fare', sa.Float(), nullable=True),
    sa.Column('tolls', sa.Float(), nullable=True),
    sa.Column('bcf', sa.Float(), nullable=True),
    sa.Column('sales_tax', sa.Float(), nullable=True),
    sa.Column('congestion_surcharge', sa.Float(), nullable=True),
    sa.Column('airport_fee', sa.Float(), nullable=True),
    sa.Column('tips', sa.Float(), nullable=True),
    sa.Column('driver_pay', sa.Float(), nullable=True),
    sa.Column('shared_request_flag', sa.String(length=1), nullable=True),
    sa.Column('shared_match_flag', sa.String(length=1), nullable=True),
    sa.Column('access_a_ride_flag', sa.String(length=1), nullable=True),
    sa.Column('wav_request_flag', sa.String(length=1), nullable=True),
    sa.Column('wav_match_flag', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
